# fly.toml for SC2CR dev sandbox
app = "sc2cr-dev"          # 👈 must match your Fly app name

[build]
  image = "registry.fly.io/sc2cr-dev:dev"

[http_service]
  internal_port = 3000      # change if your Express server listens on another port
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
