name: Auto Open PR

on:
  push:
    branches:
      - 'test/**'
      - 'docs/**'
      - 'chore/**'
  workflow_dispatch:

jobs:
  open-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Extract branch name
        id: vars
        run: |
          echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
      - name: Create pull request
        uses: actions/github-script@v7
        with:
          script: |
            const branch = '${{ steps.vars.outputs.branch }}'
            const base = 'main'
            const title = branch.startsWith('test/')
              ? `test: ${branch.replace('test/', '')}`
              : branch.startsWith('docs/')
              ? `docs: ${branch.replace('docs/', '')}`
              : branch.startsWith('chore/')
              ? `chore: ${branch.replace('chore/', '')}`
              : branch
            const body = `Automated PR for branch \`${branch}\`.\n\n- Base: \`${base}\`\n- Head: \`${branch}\`\n\nThis PR was opened by a workflow.`

            try {
              const { data: existing } = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                head: `${context.repo.owner}:${branch}`,
                state: 'open',
              })
              if (existing.length) {
                core.info(`PR already exists: #${existing[0].number}`)
                return
              }
              const { data: pr } = await github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                head: branch,
                base,
                title,
                body,
                maintainer_can_modify: true,
                draft: false,
              })
              core.info(`Opened PR #${pr.number}`)
            } catch (err) {
              core.setFailed(err.message)
            }
